### ISSUE TITLE
How did you get the pretrained models?

### ISSUE THREAD

**Issue by ZhaoweiZhu1995** [huyvnphan/PyTorch_CIFAR10#11]
Hi,

I'm wondering how are the pre-trained models obtained? For example, when I'm loading the pre-trained model for resnet18, is this pre-trained model trained using imagenet or still cifar? Thanks!

**Comment by cybertheory** [comment]
Hi Zhaowei,
 I am not the repository creator nor a contributor, but I have used the repository in the past. To my knowledge all the pre-trained models made accessible by the code in this repo were trained on all the classes of the CIFAR10 dataset. If you wanted to use this repo to train your own models with your own hardware it would train on CIFAR as well. Hope I answered your question!

**Comment by ZhaoweiZhu1995** [comment]
> Hi Zhaowei,
> I am not the repository creator nor a contributor, but I have used the repository in the past. To my knowledge all the pre-trained models made accessible by the code in this repo were trained on all the classes of the CIFAR10 dataset. If you wanted to use this repo to train your own models with your own hardware it would train on CIFAR as well. Hope I answered your question!
