### ISSUE TITLE
Hyperparameters used for training

### ISSUE THREAD

**Issue by StefanieStoppel** [huyvnphan/PyTorch_CIFAR10#20]
Hey there! 
First of all thanks for publishing this repo and the weights, it's really helpful!
I was wondering whether you used the default hyperparameters for training that are specified in the argparser of train.py, or whether you used different ones? 
I would be particularly interested in the ones for mobilenet_v2 and VGG16, if you can share. 
Thanks in advance!

**Comment by huyvnphan** [comment]
I've updated the ReadMe file with the run logs. You can see all the hyper-parameters there. In case of mobilenet_v2, here is the hyper-parameters view: https://wandb.ai/huyvnphan/cifar10/runs/3ceqnjs6/overview?workspace=user-huyvnphan

**Comment by StefanieStoppel** [comment]
Thank you, very much appreciated!
