### ISSUE TITLE
Error during download weights and even training

### ISSUE THREAD

**Issue by JosiasDMartins** [huyvnphan/PyTorch_CIFAR10#22]
I have this problem when I tried to test  the "pre-trained models" from the master branch:

> RuntimeError: Dataset not found or corrupted. You can use download=True to download it

I tried to use the version from the 2022 branch, but this version does not have a --download-weights option. I have downloaded manually the weights and extracted them into the folder, and the "corruption" message continues.

I had installed the pytorch 1.7.1 and torchvision 0.8.2, because the version 1.7.0/0.7.0 it's not currently available in pytorch repo.

Any solution for this?

**Comment by huyvnphan** [comment]
You can change line 57 of data.py to this
`dataset = CIFAR10(root=self.hparams.data_dir, train=True, transform=transform, download=True)
`
and line 75 of data.py to this
`dataset = CIFAR10(root=self.hparams.data_dir, train=False, transform=transform, download=True)
`
