### ISSUE TITLE
Do you know  FLOPs of every model?

### ISSUE THREAD

**Issue by Prines** [huyvnphan/PyTorch_CIFAR10#7]
your only show params of every model in the table,but i need FLOPs of every model,can you show me.thanks

**Comment by Prines** [comment]
hi，another question，i can not download the box by the url in your file cifar10_download.by

**Comment by huyvnphan** [comment]
No I don't have the statistic for FLOPS of every model.
I check the Box link and it is still working. However, I also add a new Google Drive link.
