### ISSUE TITLE
AdaptiveAvgPool2d in VGG creates redundancy 

### ISSUE THREAD

**Issue by lucagrementieri** [huyvnphan/PyTorch_CIFAR10#9]
In the implementation of VGG you keep the original AdaptiveAvgPool2d layer with output_size = (7, 7).
This layer creates 49 copies of the same value in the case of CIFAR10 images whose size is 32x32.

In the original VGG for ImageNet this layer has no effect because input images have  size 224x224 and the size of the output of `vgg.features` is a tensor with shape (N, 512, 7, 7). 
It is added to allow the system to be used with inputs of arbitrary sizes.

Using 32x32 images from CIFAR10, the output size of `vgg.features` is a tensor with shape (N, 512, 1, 1).
In this case the pooling layer repeat the single value 49 times to create a tensor with the desired shape.
The following linear layer has an enormous number of parameters because of this choice.

I think the pooling should be removed.

**Comment by huyvnphan** [comment]
You're right. I noticed a huge increase in GPU when I train VGG too. Feel free to creat a pull request and I'll retrain the VGG networks.

**Comment by huyvnphan** [comment]
Fixed with new version
